resource "monad_transform" "drop_low_value_fields" {
  name        = "Drop Low-Value Fields"
  description = "Drop fields from the CloudTrail records that provide little to no security detection or monitoring value."
  config      = jsondecode("{\"operations\":[{\"operation\":\"drop_key\",\"description\":\"\",\"arguments\":{\"key\":\"requestID\"}},{\"operation\":\"drop_key\",\"description\":\"\",\"arguments\":{\"key\":\"sharedEventID\"}},{\"operation\":\"drop_key\",\"description\":\"\",\"arguments\":{\"key\":\"eventVersion\"}},{\"operation\":\"drop_key\",\"description\":\"\",\"arguments\":{\"key\":\"responseElements.credentials.sessionToken\"}},{\"operation\":\"drop_key\",\"description\":\"\",\"arguments\":{\"key\":\"responseElements.credentials.expiration\"}},{\"operation\":\"drop_key\",\"description\":\"\",\"arguments\":{\"key\":\"responseElements.credentials.accessKeyId\"}},{\"operation\":\"drop_key\",\"description\":\"\",\"arguments\":{\"key\":\"additionalEventData.ExtendedRequestId\"}},{\"operation\":\"drop_key\",\"description\":\"\",\"arguments\":{\"key\":\"requestParameters.incomingTransitiveTags\"}},{\"operation\":\"jq\",\"description\":\"Drop the dashed additionalEventData key (Drop Key UI rejects dashes)\",\"arguments\":{\"key\":\"\",\"query\":\"del(.additionalEventData[\\\"x-amz-id-2\\\"])\"}}]}")
}

resource "monad_transform" "drop_cloudtrail_duplicated_data" {
  name        = "Drop CloudTrail Duplicated Data"
  description = "Drops fields from CloudTrail logs whose values are duplicated elsewhere in the CloudTrail record."
  config      = jsondecode("{\"operations\":[{\"operation\":\"drop_key\",\"description\":\"\",\"arguments\":{\"key\":\"userIdentity.sessionContext.sessionIssuer.accountId\"}},{\"operation\":\"drop_key\",\"description\":\"\",\"arguments\":{\"key\":\"recipientAccountId\"}},{\"operation\":\"drop_key\",\"description\":\"\",\"arguments\":{\"key\":\"additionalEventData.RequestDetails.awsServingRegion\"}},{\"operation\":\"drop_key\",\"description\":\"\",\"arguments\":{\"key\":\"userIdentity.invokedBy\"}},{\"operation\":\"drop_key\",\"description\":\"\",\"arguments\":{\"key\":\"userIdentity.sessionContext.sessionIssuer.principalId\"}},{\"operation\":\"drop_key\",\"description\":\"\",\"arguments\":{\"key\":\"userIdentity.sessionContext.sessionIssuer.userName\"}},{\"operation\":\"drop_key\",\"description\":\"\",\"arguments\":{\"key\":\"userIdentity.sessionContext.sessionIssuer.type\"}}]}")
}
